name: coreforecast
channels:
  - conda-forge
dependencies:
  - black
  - build
  - clang-format
  - cmake
  - mypy
  - ninja
  - numba
  - numpy
  - pytest
  - pytest-benchmark
  - scikit-build-core
  - utilsforecast>=0.0.7
  - window-ops
